### ISSUE TITLE
No whole genome sequencing dataset 

### ISSUE THREAD

**Issue by SziKayLeung** [LappalainenLab/lorals#10]
Hello, 

We would be keen to try Lorals and perform allele-specific analysis on our long-read transcriptome dataset. However, we do not have complementary whole genome sequencing dataset on the same samples for phasing. 

Wondering if it's possible to get around this and use only the sequences derived from the isoforms directly? 

Thank you

**Comment by DafniG** [comment]
Hi,
Yes this is absolutely fine. Phasing is an optional step.
Best,
