### ISSUE TITLE
Where can I find an Updated gtf/gff3 annotation for the novel transcripts discovered "Transcriptome variation in human tissues revealed by long-read sequencing" paper?

### ISSUE THREAD

**Issue by bernardo-heberle** [LappalainenLab/lorals#4]
Hello,

I looked through the main text and supplementary data and could not find an updated gtf/gff3 annotation with the novel transcripts discovered in the recently published "Transcriptome variation in human tissues revealed by long-read sequencing" article. If such an annotation is available online could you point me to it? Otherwise, would you be willing to share an updated gtf/gff3 annotation with the novel transcripts discovered in the article?

**Comment by DafniG** [comment]
Hi Bernardo,
You can use any GTF you want. If you want to use the one from the paper it can be found here, along with some other potentially useful files: https://gtexportal.org/home/datasets ([flair_filter_transcripts.gtf.gz])

**Comment by bernardo-heberle** [comment]
Great, thank you Dafni!
